### ISSUE TITLE
Caddyfile Support

### ISSUE THREAD

**Issue by NetHeritage** [mholt/caddy-dynamicdns#1]
Could u please give some clue about how to configure this app using Caddyfile.

**Comment by mholt** [comment]
Not implemented; anyone is welcome to propose one though!

**Comment by francislavoie** [comment]
I implemented Caddyfile support in #2, which uses the new functionality coming in v2.4.0 of Caddy that was added in https://github.com/caddyserver/caddy/pull/3990

🎉
