### ISSUE TITLE
Doesn't Update Cloudflare dns

### ISSUE THREAD

**Issue by gt2416** [mholt/caddy-dynamicdns#12]
When caddy first starts, it updates the dns ONLY if all the zones have different IP's to the current IP. If say I change an IP of 1 zone in cloudflare dashboard it does not update it.
Also I kept my check interval at 1m, I can see in the logs it does try to check my current IP but never updates it UNLESS I restart caddy. Then it updates it ONCE and never again. So I have to keep restarting caddy when my ip changes. This is my caddy file 
```
dynamic_dns {
                provider cloudflare {API KEY}
                domains {
                        mydomain.com @ test test1 test2
                }
                check_interval 1m
                ip_source simple_http https://icanhazip.com
                }
}

test.mydomain.com { 
 ```
**My Logs:**

```
{"level":"warn","ts":1632912662.507794,"logger":"dynamic_dns.ip_sources.simple_http","msg":"IPv6 lookup failed","endpoint":"https://icanhazip.com","error":"Get \"https://icanhazip.com\": dial tcp6 [2606:4700::6812:69c]:443: connect: no route to host"}
{"level":"warn","ts":1632912722.078304,"logger":"dynamic_dns.ip_sources.simple_http","msg":"IPv6 lookup failed","endpoint":"https://icanhazip.com","error":"Get \"https://icanhazip.com\": dial tcp6 [2606:4700::6812:69c]:443: connect: no route to host"}
{"level":"warn","ts":1632912782.1980016,"logger":"dynamic_dns.ip_sources.simple_http","msg":"IPv6 lookup failed","endpoint":"https://icanhazip.com","error":"Get \"https://icanhazip.com\": dial tcp6 [2606:4700::6812:79c]:443: connect: no route to host"}
{"level":"warn","ts":1632912842.0858293,"logger":"dynamic_dns.ip_sources.simple_http","msg":"IPv6 lookup failed","endpoint":"https://icanhazip.com","error":"Get \"https://icanhazip.com\": dial tcp6 [2606:4700::6812:69c]:443: connect: no route to host"}
{"level":"warn","ts":1632912902.5992603,"logger":"dynamic_dns.ip_sources.simple_http","msg":"IPv6 lookup failed","endpoint":"https://icanhazip.com","error":"Get \"https://icanhazip.com\": dial tcp6 [2606:4700::6812:69c]:443: connect: no route to host"}
```

**Comment by mholt** [comment]
I think you probably just don't have an IPv6-enabled network?

**Comment by mholt** [comment]
Yeah, you can use IPv4. This plugin tries both and not having an interface isn't a problem.

**Comment by gt2416** [comment]
Ah ok. So changing the ip on the cloudflare dashboard to check won’t trigger it right ? That’s how I was testing it.

**Comment by mholt** [comment]
Right, otherwise we'd have to do DNS lookups, and those are relative anyway. This plugin just checks your own IP address, and if that changes, then it updates the record.

**Comment by gt2416** [comment]
Literally just to test it. It’s a business environment so I needed to make sure it works, and my IP changes every few days or once a week, didn’t want to wait lol.
