### ISSUE TITLE
Feature request: option to only update existing records, not create new.

### ISSUE THREAD

**Issue by demifiend9** [mholt/caddy-dynamicdns#18]
I have only A record on ipv4.example.com and only AAAA record on ipv6.example.com but when I use this module, it creates the missing AAAA and A records for the subdomains which I didn't want.

Maybe something like `update_only` option which would just update existing records without creating new?

**Comment by mholt** [comment]
Hm, I think you _actually_ want #6 -- which is probably a better way to frame the problem. (Closing, but feel free to continue discussion if needed.)

**Comment by demifiend9** [comment]
Thanks for the reply.
Yes, I did look at #6 but the linked PR that is supposed to close it looked like it was only about setting IP version for the entire module. What I wanted was to specify IP version for each domain. Perhaps an easy way to do this would be ability to specify ip sources for each domain. I'd use upnp as source for my ipv4 domains (which is working beautifully) and api6.ipify.org for ipv6 domains. (Btw, how about network interface as an ip source [like this](https://github.com/TimothyYe/godns#network-interface-ip-address)? Useful for ipv6 and combined with upnp it'd make this app completely independent from ip lookup websites.)

**Comment by francislavoie** [comment]
> What I wanted was to specify IP version for each domain.

I think that would make the config pretty complicated, and would be a breaking change in the config to make it possible.

Feel free to write an alternate PR to mine, if you think you have a better solution in mind.

**Comment by demifiend9** [comment]
@francislavoie I'm extremely sorry if my reply came off as demanding or disrespectful. I'm no developer and didn't know how complicated or feasible what I suggested is. I'm fine with my current workaround of using caddy to update ipv4 records and another program for ipv6.

**Comment by francislavoie** [comment]
Sorry, my intent wasn't to be dismissive either, just wanted to clarify that this sort of change isn't necessarily "easy".

For a change not to be breaking, only new config surface would need to be added, and no _changes_. Right now since the domains are list of strings, there's no way to configure options per domain.

We _could_ have a separate, new config property that would be per-domain config, but then you'd probably be duplicating the domain in the config (domain written in two places just for ddns then once more for your actual site you're serving). That's not really elegant.

But yeah, a workaround would be to run two instances of Caddy, with the second not accepting any requests, just dealing with ddns for IPv6 or something.

**Comment by mholt** [comment]
(FWIW I don't mind having breaking changes in this module at this point, it's still early days.)

**Comment by francislavoie** [comment]
I'll work on implementing `update_only` after #16 is merged

**Comment by hussamabid** [comment]
- [ ]

**Comment by hussamabid** [comment]
> I have only A record on ipv4.example.com and only AAAA record on ipv6.example.com but when I use this module, it creates the missing AAAA and A records for the subdomains which I didn't want.
> 
> Maybe something like `update_only` option which would just update existing records without creating new?

**Comment by musklor** [comment]
Hi, thanks for your module.
Any news about this issue?
I use the ovh services but I have a new entry each time (redirection)

**Comment by mholt** [comment]
@musklor It shouldn't be creating a new record every time. That might be a bug in the OVH libdns implementation.

**Comment by musklor** [comment]
Do you think I can mix DNS ovh and dynamic DNS?
Do you think I can use ovh dyndns (login/password) with your module? For the moment I use your module with api credentials.

**Comment by mholt** [comment]
I don't know anything about OVH, sorry :(

I'd recommend filing a question or issue here: https://github.com/libdns/ovh

**Comment by musklor** [comment]
I use your module and the ovh DNS module. Can I mix both in the Caddyfile?
(For the moment, it's separate. And I use my api credentials twice)

**Comment by francislavoie** [comment]
Please use markdown code blocks when posting your config. It's extremely difficult to follow because the formatting/indentation is lost.
