### ISSUE TITLE
Cloudflare record update fails

### ISSUE THREAD

**Issue by Gandulf78** [mholt/caddy-dynamicdns#24]
Hi. 
I am trying to use your module to update my DNS records with caddy but it fails. Here are the logs:

"level":"info","ts":1650453680.2739289,"logger":"dynamic_dns","msg":"updating DNS record","zone":"mydomain.fr","type":"A","name":"test","value":"myip","ttl":1800}
{"level":"error","ts":1650453681.071767,"logger":"dynamic_dns","msg":"failed setting DNS record(s) with new IP address(es)","zone":"mydomain.fr","error":"got error status: HTTP 400: [{Code:6003 Message:Invalid request headers}]"}

Here is the global section of my caddyfile :

{ 
	debug	
	dynamic_dns {
		provider cloudflare {env.CLOUDFLARE_API_TOKEN}
		domains {
			mydomain.fr test
		}
	}
}
Otherwise I succeed to get my TLS certificates updated (ACME DNS challenge) from Cloudflare. I suppose it may be a credential issue. 
Could you please help?

Thank you.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
