### ISSUE TITLE
domain not found in DNS

### ISSUE THREAD

**Issue by ohitstom** [mholt/caddy-dynamicdns#29]
On startup it says:
`domain not found in DNS {"domain": "@"}`
then says theres a different ip address even if there isnt.
If i set the dns to something other than the servers ip, it is correctly setting it, but seems to be triggering when it doesnt need to.

my config is below:
```
{	
	dynamic_dns {
		provider cloudflare {image below}

		domains {
			url.tk @
		}
		ip_source simple_http https://icanhazip.com
		ip_source simple_http https://api64.ipify.org
		check_interval 5m
		versions ipv4
		ttl 1h
	}
}
```
[IMAGE](https://user-images.githubusercontent.com/22730962/194164820-ccbf3dee-2871-4b5c-bc64-4ba900733ebf.png)

<html>
<body>

A | url.tk | public_ip | Proxied | Auto
-- | -- | -- | -- | --

</body>
</html>

**Comment by mholt** [comment]
What are your full logs? (Unredacted please, except for credentials)

**Comment by ohitstom** [comment]
![image](https://user-images.githubusercontent.com/22730962/194172676-8f96a2a7-717e-480e-ab78-74bc6df9e23b.png)

**Comment by mholt** [comment]
Thanks, that's helpful.

You have an A record named `tompc.tk` within your `tompc.tk` zone. That looks like a mistake: `tompc.tk.tompc.tk`.

It probably should be `@`.

This doesn't appear to be an issue with this module, so I'll close this issue.

**Comment by ohitstom** [comment]
Whenever i type in @ for the name it sets it to tompc.tk
tompc.tk does resolve to tompc.tk
tompc.tk.tompc.tk does not

**Comment by mholt** [comment]
Does Cloudflare let you use .tk domains with their API? I've heard that they have restrictions on what you can do with .tk. What happens if you try a more "normal" domain?

**Comment by ohitstom** [comment]
I dont really have access to another domain, and seeing as it can change the ip regardless i wouldnt see why its a limitation.
Are you sure i havent setup my api key incorrectly as per the screenshots in the original issue?

**Comment by mholt** [comment]
I don't really know, tbh. I use this plugin with Cloudflare and it works fine for me :no_mouth: I'd recommend debugging the actual API response by putting some log.Printlns in the code or something like that.

Did it actually update the DNS record properly though? Looks like it still worked.

**Comment by ohitstom** [comment]
It is updating the record, just thinks its wrong at startup...
By any chance could i have a pic of your dns setup so i can compare? obviously with ip etc taken out.

**Comment by ohitstom** [comment]
![image](https://user-images.githubusercontent.com/22730962/194179748-190c2cd0-d0d8-47e3-ab21-886a88588ed5.png)
okay swapping between multiple vpns shows that it clearly isnt updating properly
