### ISSUE TITLE
Add ability to update additional A records.

### ISSUE THREAD

**Issue by MagnuM2K** [mholt/caddy-dynamicdns#3]
Below is possible example..
Ideally, you can point to the primary domain with a CNAME, but you usually have the default root domain and then www.

```
{
    dynamic_dns {
        domain example.com
        record_list www,@,sub
	provider gandi {env.GANDI_API_TOKEN}
	check_interval 5m
	}
}

**Comment by mholt** [comment]
Ah yeah, this is on my list... need to revisit this repo again soon.

**Comment by mholt** [comment]
Okay, done in https://github.com/mholt/caddy-dynamicdns/commit/aa9c8162558596bd1b32421838ffb842351b560b! Hope it works. :laughing:

**Comment by MagnuM2K** [comment]
This is great!!
Just tested and it worked.. But..

It created duplicate A records for both @ and www.

How I tested, I kept existing A records, but changed the IP.
Stopped Caddy/container.. Rebuilt container.. Just to make sure it was grabbing new dynamic_dns code.
Checked records on Gandi and saw that duplicate A records were in table/list.

If you need additional info or logs, let me know.

Thanks

**Comment by mholt** [comment]
@MagnuM2K What is your config?

**Comment by MagnuM2K** [comment]
Here it is..  This is more than this and obviously site.com is not my domain.. but I only included the Global options.  If you need the full config.. I'll post it, if needed.


```
{
        dynamic_dns {
                provider gandi <APIKEY>
                domains {
                        site.com @ www
                }
                check_interval 5m
        }
        debug
        acme_dns gandi <APIKEY>
        cert_issuer zerossl
        cert_issuer acme
        email webmaster@site.com
}
```

**Comment by mholt** [comment]
The TTL of 300 comes from `check_interval`, since it makes sense that the record shouldn't be cached longer than the possibility of the value changing.

This module uses `SetRecords()`, so if there is a bug or difference with how gandi is handling that, it could theoretically result in duplicate records.

**Comment by tiagosimao** [comment]
Hi there.

Bumped into the same ["bug" in the Gandi libdns](https://github.com/libdns/gandi/issues/6), got no feedback so developed a [different provider](https://codeberg.org/tiagosimao/libdns-gandi).

Just leaving this info here for future reference. Cheers.
