### ISSUE TITLE
do not update IPv6

### ISSUE THREAD

**Issue by LisonFan** [mholt/caddy-dynamicdns#32]
`config`

```caddy
{
dynamic_dns {
		provider cloudflare <API_TOKEN>
		domains {
			domain.com sub-1 sub-2
		}
		ip_source upnp
		ip_source simple_http https://icanhazip.com
		ip_source simple_http https://api64.ipify.org
		check_interval 2m
		versions ipv4 ipv6
		ttl 1m
	}
}
```

`log`

![image](https://user-images.githubusercontent.com/9424775/204202044-d12d73ff-cc61-4d33-a208-89422237bce1.png)

**Comment by francislavoie** [comment]
You used `versions ipv4 ipv6`. If you don't want IPv6 to be updated, just remove `ipv6` from there.
