### ISSUE TITLE
failed setting DNS record(s) with new IP address(es) - expected 1 zone, got 0 for [external.domain.tld]

### ISSUE THREAD

**Issue by Neon-44** [mholt/caddy-dynamicdns#33]
hey. i am currently having caddy proxy a few internal closed domains on local.domain.tld

now i wanted to open some services to the internet so i don't have to install a VPN on every device.

however, i can't get the DynDNS Module to rewrite the Domain.

the Error is the one in the Title;

```
dynamic_dns","msg":"failed setting DNS record(s) with new IP address(es)","zone":"[domain redacted]","error":"expected 1 zone, got 0 for [domain redacted]"}
```

does anyone have an idea what the Problem could be?

**Comment by francislavoie** [comment]
It's impossible to help without more information.

Please share your full config, your full logs, and do not redact domain names. Domains are not secret information, since they're public via certificate transparency logs https://crt.sh/

**Comment by Neon-44** [comment]
i was already collecting my configs and logs, when i found the Error.

i entered external.domain.tld into the dyndns block, when there doesn't exist any external.domain.tld zone, but only a domain.tld

i feel a bit stupid now.

anyways, thank you very much for your readiness to help me, @francislavoie, i really appreciate it a lot :)

btw, is there a way that dynamic_domains only opens domains that end with external.domain.tld and leaves local.domain.tld alone, or should i find a nameserver that allows for the creation of new zones?

**Comment by Neon-44** [comment]
for anyone wondering how i did it in the end:

```
domain.tld *.external
```

it works well enough i guess
