### ISSUE TITLE
Enable Cloudflare Proxy Status

### ISSUE THREAD

**Issue by kpinarci** [mholt/caddy-dynamicdns#36]
Hi there, firstly, thanks a lot for the super cool modules for Caddy. It's exactly what I was looking for. Is there a way to enable the Cloudflare proxy status via API? I haven't found that option.

https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records/

**Comment by francislavoie** [comment]
That seems out of scope of this plugin. We want to avoid any provider-specific logic. A separate plugin more catered towards Cloudflare could probably do that though.

**Comment by kpinarci** [comment]
Good to know, thank you!

**Comment by mholt** [comment]
That's kind of an interesting idea though -- a Cloudflare plugin that integrates a variety of Cloudflare APIs/services? Could be useful, maybe.

I wonder what @jahands may think of an idea like this.

**Comment by mholt** [comment]
@jahands I'll build it with a Cloudflare sponsorship :smiley:

**Comment by kpinarci** [comment]
Thank you very much! I'm sure there are plenty of others out there who are also looking forward to it.

**Comment by rushiiMachine** [comment]
Any update on this?

**Comment by jahands** [comment]
Omg sorry @mholt I completely missed this - I get too many GitHub emails :(

**Comment by rushiiMachine** [comment]
I ended up running a separate container for DDNS that supports creating proxied records: https://github.com/qdm12/ddns-updater

**Comment by mholt** [comment]
@jahands I know the feeling!! lol. I had to disable most of my notifications.
