### ISSUE TITLE
dynamic_dns is thowing error - server response was: 503 503 Service Unavailable"}

### ISSUE THREAD

**Issue by MagnuM2K** [mholt/caddy-dynamicdns#4]
I've configured the dynamic_dns module in the Global options block in my Caddyfile.

When I restart the caddy docker container, it works without issue.. Then subsequest refreshes generate errors.

Using Caddy 2.4.0 beta1.. or close to it.  This is my Dockerfile.

```
FROM caddy:builder AS builder

RUN xcaddy build bafb562991598df703a744e13cbc06472e71349e \
    --with github.com/mholt/caddy-dynamicdns \
    --with github.com/caddy-dns/gandi

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
And this is my Caddyfile that handles the dns update.
```
{
        dynamic_dns {
                domain www.site.com
                provider gandi <APIKEY>
                check_interval 5m
        }
        acme_dns gandi <APIKEY>
        email webmaster@site.com
}
```
This is the log of the dns update and failure.

```
{"level":"error","ts":1614279644.7509358,"logger":"dynamic_dns","msg":"checking IP address","error":"server response was: 503 503 Service Unavailable"}
{"level":"info","ts":1614280082.1940167,"logger":"dynamic_dns","msg":"IP address changed","last_ip":"<nil>","new_ip":"XX.XX.XX.XX"}
{"level":"info","ts":1614280082.1940715,"logger":"dynamic_dns","msg":"updating DNS record","type":"A","name":"www.site.com","value":"XX.XX.XX.XX","ttl":300}
{"level":"info","ts":1614280082.9069586,"logger":"dynamic_dns","msg":"finished updating DNS"}
{"level":"error","ts":1614296010.809118,"logger":"dynamic_dns","msg":"checking IP address","error":"server response was: 503 503 Service Unavailable"}
{"level":"error","ts":1614298080.8029675,"logger":"dynamic_dns","msg":"checking IP address","error":"server response was: 503 503 Service Unavailable"}
{"level":"error","ts":1614299280.7873015,"logger":"dynamic_dns","msg":"checking IP address","error":"server response was: 503 503 Service Unavailable"}
{"level":"error","ts":1614299580.7971187,"logger":"dynamic_dns","msg":"checking IP address","error":"server response was: 503 503 Service Unavailable"}
```

**Comment by fu-sen** [comment]
The log shows a successful update completion:

```
{"level":"info","ts":1614280082.1940167,"logger":"dynamic_dns","msg":"IP address changed","last_ip":"<nil>","new_ip":"XX.XX.XX.XX"}
{"level":"info","ts":1614280082.1940715,"logger":"dynamic_dns","msg":"updating DNS record","type":"A","name":"www.site.com","value":"XX.XX.XX.XX","ttl":300}
{"level":"info","ts":1614280082.9069586,"logger":"dynamic_dns","msg":"finished updating DNS"}
```

Perhaps `503` really feels like a temporary problem returned by the API server.

**Comment by mholt** [comment]
Hmm, yeah, it looks like Gandi's API was probably down at the time.

**Comment by MagnuM2K** [comment]
Hi Matt,

It doesn't feel like a Gandi API issue.. It seems like it's ipify.org that is timing out or taking long.

I issued this command directly on my host.. and it took about 10-15 secs for it to return the IP.

curl https://api.ipify.org/
xxx.xx.xxx.xx

Could you try or use a different public ip server? 
ex: icanhazip.com

**Comment by mholt** [comment]
Oh, right, I see. Yeah, the IP source is modular: https://github.com/mholt/caddy-dynamicdns/blob/master/ipsource.go

I suppose we could add support for multiple IP source modules so if one is down it can try the next one.

**Comment by MagnuM2K** [comment]
Here's another public ip alternative.

http://me.gandi.net

And there are many others.. You choose.

**Comment by fu-sen** [comment]
> I issued this command directly on my host.. and it took about 10-15 secs for it to return the IP.
> 
> curl https://api.ipify.org/
> xxx.xx.xxx.xx

This is obviously slow to respond and seems to be very heavy on the Gandi API server.
You may consider other name server systems.

**Comment by mholt** [comment]
Pushed some better IP sourcing code with redundancy built in.
