### ISSUE TITLE
Feature Request - Add ability to either request IPv4, IPv6 or both.. (Or disable IPv6)

### ISSUE THREAD

**Issue by MagnuM2K** [mholt/caddy-dynamicdns#6]
My logs are constantly showing attempts to request IPv6.  If we know that we don't have IPv6 or our ISP doesn't support it, it would be nice to either disable it, or via some parameter, only request IPv4.

```
{"level":"warn","ts":1614694441.669056,"logger":"dynamic_dns.ip_sources.simple_http","msg":"IPv4 lookup failed","endpoint":"https://api.ipify.org","error":"https://api.ipify.org: server response was: 503 503 Service Unavailable"}
{"level":"warn","ts":1614694441.67404,"logger":"dynamic_dns.ip_sources.simple_http","msg":"IPv6 lookup failed","endpoint":"https://api.ipify.org","error":"Get \"https://api.ipify.org\": dial tcp6: address api.ipify.org: no suitable address found"}
{"level":"warn","ts":1614694441.8593335,"logger":"dynamic_dns.ip_sources.simple_http","msg":"IPv6 lookup failed","endpoint":"https://myip.addr.space","error":"Get \"https://myip.addr.space\": dial tcp6 [2607:5300:203:d0:1::d089]:443: connect: cannot assign requested address"}
{"level":"warn","ts":1614694741.6912205,"logger":"dynamic_dns.ip_sources.simple_http","msg":"IPv6 lookup failed","endpoint":"https://api.ipify.org","error":"Get \"https://api.ipify.org\": dial tcp6: address api.ipify.org: no suitable address found"}
```

**Comment by mholt** [comment]
Yeah, I have the same thing in my logs... they're harmless, really; but I'll see if I can get around to making the IP versions configurable.

**Comment by fu-sen** [comment]
Yes, I saw this and referred to https://api.ipify.org/ , but it took a lot of time to respond. This is definitely a problem with api.ipify.org and you should look elsewhere.

Link my Forum post earlier. Here is a list of this server:
https://caddy.community/t/caddy-server-that-returns-only-ip-address-as-text/6928

**Comment by mouzzampk2014** [comment]
Would be great to have this added. Is there any update on this? :)

Thank you

**Comment by mouzzampk2014** [comment]
Thank you its working awesome :)
