### ISSUE TITLE
Add desec.io

### ISSUE THREAD

**Issue by rugk** [mholt/caddy-dynamicdns#8]
https://desec.io/ is awesome and has a pretty good featurefull REST api: https://desec.readthedocs.io/en/latest/dns/domains.html 

It would be great if you could support it.

**Comment by francislavoie** [comment]
Support for DNS providers is via libdns.

See https://caddy.community/t/writing-new-dns-provider-modules-for-caddy/7786

**Comment by rugk** [comment]
Okay, good to hear thanks. The go template there looks simple enough and it's always good to have a reusable (go) library. 

/cc @peterthomassen

**Comment by mholt** [comment]
Yeah, Francis is right; libdns is the place for this. Totally reusable, works for the ACME DNS challenge and any other DNS record needs too!

Will close this particular issue but leave the one in libdns open; feel free to continue discussion if needed.
