### ISSUE TITLE
Cloudflare record update authorization issue

### ISSUE THREAD

**Issue by tecosaur** [mholt/caddy-dynamicdns#80]
This plugin looks brilliant! I'm having trouble getting it to work though. I'm using the same Cloudflare token that I sucesfully used with the DNS plugin and ACME, and tried generating a new token too after seeing #24. Unfortunately, I keep on seeing the same errors:

```
Dec 29 23:13:37 golgi systemd[1]: Started Caddy.
Dec 29 23:13:37 golgi caddy[366499]: {"level":"error","ts":1735514017.5611193,"logger":"dynamic_dns","msg":"unable to lookup current IPs from DNS records","error":"got error status: HTTP 400: [{Code:6003 Message:Invalid request headers ErrorChain:[{Code:6111 Message:Invalid format for Authorization header}]}]"}
Dec 29 23:13:37 golgi caddy[366499]: {"level":"error","ts":1735514017.7073393,"logger":"dynamic_dns","msg":"failed setting DNS record(s) with new IP address(es)","zone":"tecosaur.net","error":"got error status: HTTP 400: [{Code:6003 Message:Invalid request headers ErrorChain:[{Code:6111 Message:Invalid format for Authorization header}]}]"}
```

This is with the config:

```
{
	acme_dns cloudflare {env.CLOUDFLARE_AUTH_TOKEN}
	dynamic_dns {
		provider cloudflare {env.CLOUDFLARE_API_TOKEN}
		domains {
			tecosaur.net @ ssh
		}
	}

	log {
		level ERROR
	}
}
```

I've given the CF token these permissions: `DNS Settings:Edit`, `DNS Settings:Read`, `DNS:Read`, `DNS:Edit`.

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by mholt** [comment]
This means your token is incorrect or missing -- make sure the env variable is set for the Caddy process.

**Comment by tecosaur** [comment]
Thanks for getting back to me Matt! I agree that seems like the obvious conclusion from the message, but there are two things that make me think it's not the case:
1. Checking `cat /proc/PID/environ` the env var is indeed set
2. The `acme_dns` configuration is working
